import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "School Management App",
  description: "Generated by create next app",
};
// className={`${geistSans.variable} ${geistMono.variable}`}

export default function RootLayout({ children }) {
  return (
    <html className={`${geistSans.variable} ${geistMono.variable}`} lang="en">
      <body>
        {children}
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
